### ISSUE TITLE
Versioning della documentazione

### ISSUE THREAD

**Issue by andreabalducci** [Microarea/MigrazioneMago4#1]
Il wiki standard di GitHub non è abbastanza flessibile per gestire qualsiasi cosa che debba essere versionato e abbia più di qualche pagina.

Le opzioni più comuni sono:
1) il wiki è fatto di markdown interni al repository git così sono forkabili e potete accettare PR. Inoltre il tutto è versionabile e taggabile
2) si usa ReadTheDocs che di fatto è lo standard (la documentazione della maggior parte dei progetti GitHub sta migrando lì).

**Comment by andrea-rinaldi-microarea** [comment]
Suggerimento interessante, grazie.
Il markdown interno al repository lo avevamo scartato sia per una questione di immediatezza e semplicità nella compilazione che per il fatto che non prevedevamo una gestione complessa con PR, fork e via discorrendo. 
ReadTheDocs è una soluzione molto completa; più che per queste pagine, che sono limitate ed avranno una vita evolutiva ridotta, sarà una scelta da valutare per la documentazione del prodotto "tout court" (l'attuale Help Center).
