### ISSUE TITLE
Microarea AddIn su VS2017 

### ISSUE THREAD

**Issue by Vimmordino** [Microarea/MigrazioneMago4#2]
Con il pacchetto distribuito nella beta non si riesce a installare, messaggio d'errore:
> Questa estensione non è installabile su nessuno dei prodotti attualmente installati

vestione di VS 2017 professional v 15.2

**Comment by andrea-rinaldi-microarea** [comment]
Questo progetto riguarda esclusivamente la documentazione sul porting, quindi le issues si devono riferire esclusivamente al contenuto delle pagine di Wiki.
Comunque l'AddIn per VS 2017 è in fase di pubblicazione

**Comment by Vimmordino** [comment]
Grazie mille!

**Comment by andreabalducci** [comment]
@andrea-rinaldi-microarea significa che ad oggi non è possibile migrare perché non ci sono tutti i tool necessari? Tra wiki e quello che ho installato ci sono delle discrepanze (vedi #3 )

**Comment by andreabalducci** [comment]
Link per l'addin https://marketplace.visualstudio.com/items?itemName=vs-publisher-861779.MicroareaExtension2017

**Comment by Vimmordino** [comment]
grazie @andreabalducci !
