### ISSUE TITLE
Versione di VS Richiesta

### ISSUE THREAD

**Issue by andreabalducci** [Microarea/MigrazioneMago4#3]
Nella documentazione si indica

    La migrazione delle solutions consiste nel passaggio a Visual Studio 2015

poi seguono le istruzioni per VS 2017.

Il MicroareaAddin presente nei sorgenti propone l'installazione solamente per VS2015.
Se apro la solution di Mago da VS2017 ho indicazione che sono progetti per VS2015.

Qual'è la piattaforma dev di riferimento per Mago4 2.x?

**Comment by andreabalducci** [comment]
Con vs 2015 non compila per un errore di link relativo al SDK di windows (mt.exe), su 2017 compila ma secondo Solution Explorer i progetti dei sorgenti standard sono ancora VS2015.

![image](https://user-images.githubusercontent.com/212729/27853331-8d4f2844-6162-11e7-940c-b9f971a12eed.png)

**Comment by gianfri** [comment]
confermo ... VS2017 compila e i progetti sono VS2015.
Il problema dell'addin e`  la creazione delle virtual directory (che sono parecchie ....).
Ora provo con ClickOnceDeployer ,,,,

**Comment by gianfri** [comment]
![capture](https://user-images.githubusercontent.com/29854909/27853780-6ce4fd02-6164-11e7-96e3-86eaddc61b06.JPG)

**Comment by andreabalducci** [comment]
@gianfri l'addin è sul marketplace. L'ho usato per creare le cartelle virtuali su IIS e pare fare il suo dovere come previsto (non ho ancora mandato in run mago).

**Comment by andrea-rinaldi-microarea** [comment]
`La migrazione delle solutions consiste nel passaggio a Visual Studio 2015`
corretto il testo

**Comment by andreabalducci** [comment]
nella [documentazione ](https://github.com/Microarea/MigrazioneMago4/wiki/Passaggio-a-Visual-Studio-2017) inerente l'installer project viene linkato il plug-in per 2015 e non per [2017 ](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2017InstallerProjects)

**Comment by andrea-rinaldi-microarea** [comment]
`nella documentazione inerente l'installer project viene linkato il plug-in per 2015 e non per 2017`
aggiunta nota sull'installazione del plug-in dalla gallery.
Dal prossimo master la beta non avrà più il vecchio plug-in per non indurre in errore.
