### ISSUE TITLE
Configurazione Ambiente di Sviluppo

### ISSUE THREAD

**Issue by andreabalducci** [Microarea/MigrazioneMago4#4]
Ho compilato e mandato in esecuzione con successo Mago4 senza installare UWP ed Extension development perché non configurati sulle workstation di sviluppo.

Per quale motivo vengono indicati come prerequisiti per l'ambiente? 
Che funzionalità ci perdiamo nello sviluppo dei verticali senza UWP?

**Comment by mtalotta** [comment]
Buongiorno Andrea,
per il  porting dei verticali in TB Studio, oggetto della documentazione non sono necessari UWP ed Extension development, per questo li ho eliminate anche dalla documentazione.
