### ISSUE TITLE
platform toolset 140 (per compatibilità soluzioni VS2015)

### ISSUE THREAD

**Issue by Vimmordino** [Microarea/MigrazioneMago4#5]
Avendo una macchina nuova con solo Visual studio 2017 a bordo non si è installato di default con gli strumenti per la compilazione v140, quindi non upgradando ERP mi dava errore in compilazione perchè mancava il toolset.
La soluzione è in questi passaggi:
- Launch the "Microsoft Visual Studio Installer" from your start menu.
- Select "Modify" for the instance of Visual Studio 2017 you have installed.
- Under the "Summary" pane of the workload selector, click the "Desktop development with C++" expander (if it is collapsed)
- Check the "VC++ 2015.3 v140 toolset (x86,x64)" optional feature.

[qui la fonte](https://developercommunity.visualstudio.com/content/problem/48806/cant-find-v140-in-visual-studio-2017.html)

La posto qui, spero sia il posto giusto nel caso qualcuno si trovasse nella mia stessa situazione.
Magari si può inserire nella documentazione.

**Comment by andrea-rinaldi-microarea** [comment]
ottimo @Vimmordino, nel frattempo abbiamo aggiornato la documentazione indicando quali componenti di VS 2017 serve installare: [Configurazione Ambiente di sviluppo](https://github.com/Microarea/MigrazioneMago4/wiki/Configurazione-ambiente-di-sviluppo)
